const lines = [
  "Lowcap Bot CLI Hub",
  "",
  "Available commands:",
  "",
  "pnpm import -- --mint <MINT> --name <NAME> --symbol <SYM>",
  "  Import one token candidate, score it, and save Token/Dev data.",
  '  Example: pnpm import -- --mint TESTMINT --name "basic token" --symbol BTK',
  "",
  "pnpm import:mint -- --mint <MINT> [--source <SOURCE>]",
  "  Create the minimum Token row for mint-driven accumulation without scoring or notify.",
  "  Example: pnpm import:mint -- --mint TESTMINT --source manual",
  "",
  "pnpm import:mint:file -- --file <PATH>",
  "  Read one JSON object with an items array and forward each item into pnpm import:mint sequentially.",
  '  Example: pnpm import:mint:file -- --file ./tmp/mint-batch.json',
  "",
  "pnpm import:mint:source-file -- --file <PATH>",
  "  Read one source-specific raw event object, normalize it to the minimum mint handoff payload, and forward it into pnpm import:mint.",
  '  Example: pnpm import:mint:source-file -- --file ./examples/import-mint-source-file.sample.json',
  "",
  "pnpm token:enrich -- --mint <MINT> --name <NAME> --symbol <SYMBOL> [--desc <TEXT>] [--source <SOURCE>]",
  "  Fill current token fields after mint-only import without rescoring or notify.",
  '  Example: pnpm token:enrich -- --mint TESTMINT --name "basic token" --symbol BTK --desc "manual enrich"',
  "",
  "pnpm token:rescore -- --mint <MINT>",
  "  Recompute hard reject and score fields from the current token text without notify.",
  "  Example: pnpm token:rescore -- --mint TESTMINT",
  "",
  "pnpm import:min -- --mint <MINT> --name <NAME> --symbol <SYM> [--source <SOURCE>] [--desc <TEXT>] [--dev <WALLET>]",
  "  Thin manual-intake wrapper around pnpm import for the common minimum fields.",
  '  Example: pnpm import:min -- --mint TESTMINT --name "basic token" --symbol BTK --source manual',
  "",
  "pnpm import:file -- --file <PATH>",
  "  Read one JSON object from a file and forward it into pnpm import.",
  '  Example: pnpm import:file -- --file ./tmp/token.json',
  "",
  'pnpm trend:update -- --keywords "ai,anime,base" [--ttlHours 24]',
  "  Refresh trend keywords used by trend scoring.",
  '  Example: pnpm trend:update -- --keywords "ai,anime,base" --ttlHours 24',
  "",
  "pnpm token:show -- --mint <MINT>",
  "  Show one saved Token in detail as JSON.",
  "  Example: pnpm token:show -- --mint TESTMINT",
  "",
  "pnpm token:compare -- --mint <MINT>",
  "  Show entrySnapshot, current token fields, latestMetric, and recentMetrics as JSON.",
  "  Example: pnpm token:compare -- --mint TESTMINT",
  "",
  "pnpm metric:add -- --mint <MINT> [--source <SOURCE>] [--launchPrice <NUM>] [--peakPrice15m <NUM>] [--peakPrice1h <NUM>] [--maxMultiple15m <NUM>] [--maxMultiple1h <NUM>] [--peakFdv24h <NUM>] [--volume24h <NUM>] [--timeToPeakMinutes <NUM>]",
  "  Append one Metric row for an existing token without updating the token itself.",
  "  Example: pnpm metric:add -- --mint TESTMINT --peakFdv24h 180000 --volume24h 42000",
  "",
  "pnpm tokens:report -- [--rank <RANK>] [--source <SOURCE>] [--hardRejected <true|false>] [--limit 20]",
  "  Show recent saved Token rows as JSON.",
  "  Example: pnpm tokens:report -- --source manual --hardRejected false --limit 10",
  "",
  "pnpm tokens:compare-report -- [--rank <RANK>] [--source <SOURCE>] [--metadataStatus <STATUS>] [--limit 20]",
  "  Show recent saved Token rows as entry-vs-outcome comparison JSON.",
  "  Example: pnpm tokens:compare-report -- --metadataStatus enriched --limit 10",
  "",
  "pnpm metric:show -- --id <ID>",
  "  Show one saved Metric in detail as JSON.",
  "  Example: pnpm metric:show -- --id 1",
  "",
  "pnpm metrics:report -- [--mint <MINT>] [--tokenId <ID>] [--source <SOURCE>] [--rank <RANK>] [--limit 20]",
  "  Show recent saved Metric rows as JSON.",
  "  Example: pnpm metrics:report -- --source manual --rank A --limit 5",
  "",
  "pnpm smoke",
  "  Run a lightweight operational check for the core MVP flows.",
  "  Example: pnpm smoke",
];

console.log(lines.join("\n"));
