const lines = [
  "Lowcap Bot CLI Hub",
  "",
  "Available commands:",
  "",
  "pnpm import -- --mint <MINT> --name <NAME> --symbol <SYM>",
  "  Import one token candidate, score it, and save Token/Dev data.",
  '  Example: pnpm import -- --mint TESTMINT --name "basic token" --symbol BTK',
  "",
  "pnpm import:mint -- --mint <MINT> [--source <SOURCE>]",
  "  Create the minimum Token row for mint-driven accumulation without scoring or notify.",
  "  Example: pnpm import:mint -- --mint TESTMINT --source manual",
  "",
  "pnpm import:mint:file -- --file <PATH>",
  "  Read one JSON object with an items array and forward each item into pnpm import:mint sequentially.",
  '  Example: pnpm import:mint:file -- --file ./tmp/mint-batch.json',
  "",
  "pnpm import:mint:source-file -- --file <PATH>",
  "  Read one source-specific raw event object, normalize it to the minimum mint handoff payload, and forward it into pnpm import:mint.",
  '  Example: pnpm import:mint:source-file -- --file ./examples/import-mint-source-file.sample.json',
  "",
  "pnpm detect:dexscreener:token-profiles [--file <PATH>] [--limit <N>] [--write] [--watch] [--intervalSeconds <N>] [--maxIterations <N>] [--checkpointFile <PATH>]",
  "  Dry-run by default; with --watch --write, repeat the cycle, persist a simple checkpoint cursor, and continue after cycle-level errors.",
  '  Example: pnpm detect:dexscreener:token-profiles -- --file ./fixtures/source-events/dexscreener-token-profiles-latest-v1.solana-pzcekaa.json',
  "",
  "pnpm detect:geckoterminal:new-pools [--file <PATH>] [--write] [--watch] [--intervalSeconds <N>] [--maxIterations <N>] [--checkpointFile <PATH>]",
  "  Dry-run by default; with --watch --write, repeat GeckoTerminal new_pools cycles, persist a simple checkpoint cursor, retry one fetch-only 429 once after a short backoff, and continue after cycle-level errors.",
  "  Example: pnpm detect:geckoterminal:new-pools -- --file ./fixtures/source-events/geckoterminal-new-pools.solana-wtf-first-item.json --watch --write --maxIterations 2 --checkpointFile /tmp/gecko-checkpoint.json",
  "",
  "pnpm compare:geckoterminal:dexscreener [--timeoutSeconds <N>] [--intervalSeconds <N>]",
  "  Fetch one live GeckoTerminal mint candidate, then bounded-poll DexScreener token profiles latest v1 and print comparison JSON only.",
  "  Example: pnpm compare:geckoterminal:dexscreener -- --timeoutSeconds 60 --intervalSeconds 5",
  "",
  "pnpm token:enrich -- --mint <MINT> [--name <NAME>] [--symbol <SYMBOL>] [--desc <TEXT>] [--source <SOURCE>]",
  "  Fill or patch current token fields after mint-only import without rescoring or notify.",
  '  Example: pnpm token:enrich -- --mint TESTMINT --name "basic token" --symbol BTK --desc "manual enrich"',
  "",
  "pnpm token:rescore -- --mint <MINT>",
  "  Recompute hard reject and score fields from the current token text without notify.",
  "  Example: pnpm token:rescore -- --mint TESTMINT",
  "",
  "pnpm token:enrich-rescore:geckoterminal -- [--mint <MINT>] [--limit <N>] [--sinceMinutes <N>] [--write] [--notify]",
  "  Dry-run by default; fetch GeckoTerminal token snapshots for recent Gecko-origin tokens that are still missing name or symbol, preview enrich plus rescore, write both stages only with --write, notify only with --write --notify when a token newly enters S-rank without hard reject, and stop the current batch early after the first 429 token snapshot error.",
  "  Example: pnpm token:enrich-rescore:geckoterminal -- --limit 10 --sinceMinutes 180 --write --notify",
  "",
  "pnpm import:min -- --mint <MINT> --name <NAME> --symbol <SYM> [--source <SOURCE>] [--desc <TEXT>] [--dev <WALLET>]",
  "  Thin manual-intake wrapper around pnpm import for the common minimum fields.",
  '  Example: pnpm import:min -- --mint TESTMINT --name "basic token" --symbol BTK --source manual',
  "",
  "pnpm import:file -- --file <PATH>",
  "  Read one JSON object from a file and forward it into pnpm import.",
  '  Example: pnpm import:file -- --file ./tmp/token.json',
  "",
  'pnpm trend:update -- --keywords "ai,anime,base" [--ttlHours 24]',
  "  Refresh trend keywords used by trend scoring.",
  '  Example: pnpm trend:update -- --keywords "ai,anime,base" --ttlHours 24',
  "",
  "pnpm token:show -- --mint <MINT>",
  "  Show one saved Token's current snapshot as JSON, including hasCurrentText, enrichedAt, and rescoredAt.",
  "  Example: pnpm token:show -- --mint TESTMINT",
  "",
  "pnpm token:compare -- --mint <MINT>",
  "  Show entry-vs-current diff plus latestMetric and recentMetrics as JSON.",
  "  Example: pnpm token:compare -- --mint TESTMINT",
  "",
  "pnpm metric:add -- --mint <MINT> [--source <SOURCE>] [--launchPrice <NUM>] [--peakPrice15m <NUM>] [--peakPrice1h <NUM>] [--maxMultiple15m <NUM>] [--maxMultiple1h <NUM>] [--peakFdv24h <NUM>] [--volume24h <NUM>] [--timeToPeakMinutes <NUM>]",
  "  Append one Metric row for an existing token without updating the token itself.",
  "  Example: pnpm metric:add -- --mint TESTMINT --peakFdv24h 180000 --volume24h 42000",
  "",
  "pnpm metric:snapshot:geckoterminal -- [--mint <MINT>] [--limit <N>] [--sinceMinutes <N>] [--minGapMinutes <N>] [--source <SOURCE>] [--write] [--watch] [--intervalSeconds <N>] [--maxIterations <N>]",
  "  Dry-run by default; with --watch, repeat snapshot cycles, continue after cycle-level errors, optionally skip recent token+source metrics with --minGapMinutes, and stop the current cycle early after the first 429 token snapshot error.",
  "  Example: pnpm metric:snapshot:geckoterminal -- --limit 5 --sinceMinutes 120 --watch --intervalSeconds 60 --minGapMinutes 10",
  "",
  "pnpm tokens:report -- [--rank <RANK>] [--source <SOURCE>] [--metadataStatus <STATUS>] [--hasMetrics <true|false>] [--hardRejected <true|false>] [--createdAfter <ISO8601>] [--limit 20]",
  "  Show current token inventory rows as JSON, including createdAt, updatedAt, enrichedAt, and rescoredAt.",
  "  Example: pnpm tokens:report -- --source manual --metadataStatus mint_only --createdAfter 2026-04-16T00:00:00.000Z --limit 10",
  "",
  "pnpm tokens:compare-report -- [--rank <RANK>] [--source <SOURCE>] [--metadataStatus <STATUS>] [--limit 20]",
  "  Show entry-vs-current comparison rows as JSON.",
  "  Example: pnpm tokens:compare-report -- --metadataStatus enriched --limit 10",
  "",
  "pnpm metric:show -- --id <ID>",
  "  Show single metric detail as JSON.",
  "  Example: pnpm metric:show -- --id 1",
  "",
  "pnpm metrics:report -- [--mint <MINT>] [--tokenId <ID>] [--source <SOURCE>] [--rank <RANK>] [--limit 20]",
  "  Show filtered metric inventory/report rows as JSON.",
  "  Example: pnpm metrics:report -- --source manual --rank A --limit 5",
  "",
  "pnpm smoke",
  "  Run a lightweight operational check for the core MVP flows.",
  "  Example: pnpm smoke",
];

console.log(lines.join("\n"));
